### ISSUE TITLE
Need to ask user's permission before running gallery view activity for selecting images for post

### ISSUE THREAD

**Issue by yogendra131994** [yogendra131994/Social_Media_App#2]
![Screenshot_20230805_104709](https://github.com/yogendra131994/Social_Media_App/assets/87609565/ac83e3e6-381c-4fae-a505-24f57083935d)

The image above shows bottom navigation of the application. The middle icon shows the upload button as + sign. On clicking + icon you will be redirected to choose image from gallery activity as shown below. 

![IMG_20230805_114707](https://github.com/yogendra131994/Social_Media_App/assets/87609565/124b2d9b-3fd7-4347-b135-fa57626f1a95)

The issue is that the application does not ask for user's permission, I want to ensure that app asks for permission before accessing user's media.

You can look up for the related code here [(app/src/main/java/com/example/myapplication/activities/MainActivity.kt)](https://github.com/yogendra131994/Social_Media_App/blob/main/app/src/main/java/com/example/myapplication/activities/MainActivity.kt#L146C4-L202C1)

**Comment by HarshPanchal18** [comment]
May I resolve this?

**Comment by yogendra131994** [comment]
> @yogendra131994 May I resolve this?

Yes, Please. Looking forward towards more contributions.
